version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: pg_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - pg_db
#      - mongo_db
    restart: unless-stopped

  nginx:
    image: nginx:1.25.2
    restart: unless-stopped
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
      BACKEND_HOST: backend
      BACKEND_PORT: 3000
      MONGO_WEB_HOST: mongo_web
      MONGO_WEB_PORT: 80
      PG_WEB_HOST: pg_web
      PG_WEB_PORT: 80
    depends_on:
      - backend
      - pg_web
      - mongo_web
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"

  pg_db:
    image: postgis/postgis:15-3.3
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
      PGTZ: ${TZ}
    volumes:
      - ./pg_db/init/:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data

  pg_web:
    image: dpage/pgadmin4:7.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - ./pg_web/servers.json:/pgadmin4/servers.json
    depends_on:
      - pg_db

  mongo_db:
    image: mongo:6-jammy
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      TZ: ${TZ}
    volumes:
      - ./mongo_db/init/:/docker-entrypoint-initdb.d/
      - mongo_data:/data/db

  mongo_web:
    image: mongo-express:1.0.0-20
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo_db:27017/${MONGO_DB}?ssl=false&authSource=admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
      ME_CONFIG_SITE_BASEURL: /admin/mongo
      PORT: 80
    depends_on:
      - mongo_db

volumes:
  pg_data:
  mongo_data: